// Auto-generated by generateDealershipNames.js
window.DEALERSHIPS = [
  "Alpine-Overland",
  "Asbury",
  "axio",
  "Fast-Start-Auto",
  "Fiuza-Motors",
  "Generous-Auto",
  "Jerry-Seiner-GMC-South-Jordan",
  "Jerry-Seiner-Kia-South-Jordan",
  "Low-Book-Sales",
  "Mark-Miller-Subaru-Southtowne",
  "National-Auto-Plaza",
  "other",
  "Peterson-Auto-Sales",
  "Prestman-Auto",
  "Riverton-Chevrolet",
  "Southtowne-Mitsubishi",
  "Stockton-12-Honda",
  "Template",
  "Tim-Dahle-Mazda-Southtowne",
  "Tim-Dahle-Nissan-Southtowne",
  "Volkswagen-Southtowne"
];
