// generateDealershipNames.js

const fs = require("fs");
const path = require("path");

const dealershipsPath = path.join(__dirname, "..", "projects", "dealerships");
const outputPath = path.join(__dirname, "..", "assets", "js", "dealershipNames.js");

fs.readdir(dealershipsPath, { withFileTypes: true }, (err, entries) => {
  if (err) {
    console.error("Error reading dealership projects folder:", err.message);
    process.exit(1);
  }

  const folders = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  // Always include "other"
  folders.push("other");

  // Remove duplicates + sort
  const unique = Array.from(new Set(folders)).sort((a, b) =>
    a.localeCompare(b)
  );

  // Log to console
  console.log("Dealerships found:");
  unique.forEach((folder) => console.log(folder));

  // Build JS file contents
  const jsContent =
    `// Auto-generated by generateDealershipNames.js\n` +
    `window.DEALERSHIPS = ${JSON.stringify(unique, null, 2)};\n`;

  // Write dealershipNames.js (the file the HTML pages load)
  fs.writeFile(outputPath, jsContent, (writeErr) => {
    if (writeErr) {
      console.error("Error writing JS file:", writeErr.message);
      process.exit(1);
    }
    console.log(`\n✔ dealershipNames.js created/updated successfully.`);
  });
});
